Models/Donormodel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_set_a.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDonorEntities : DbContext
    {
        public DBDonorEntities()
            : base("name=DBDonorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDonor> TBLDonors { get; set; }
    }
}

Models/Donormodel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\aks82\source\repos\Internal_set_a\Models\Donormodel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Donormodel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Models/TBLDonor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_set_a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDonor
    {
        public int ID_PK { get; set; }
        public string Name { get; set; }
        public System.DateTime Donation_Date { get; set; }
        public string City { get; set; }
        public string Aadhar_Number { get; set; }
        public int Donation_Amount { get; set; }
    }
}

Controllers/DonorController.cs
using Internal_set_a.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Internal_set_a.Controllers
{
    public class DonorController : Controller
    {
        DBDonorEntities con=new DBDonorEntities();
        // GET: Donor
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult insert(TBLDonor d)
        {
            if(d.Donation_Amount<9999)
            {
                return View("Message");
            }
            else
            {
                con.TBLDonors.Add(d);
                con.SaveChanges();
                return RedirectToAction("GetAll");
            }
            
        }
        public ActionResult GetAll()
        {
            List<TBLDonor> tBLDonors=con.TBLDonors.ToList();
            return View(tBLDonors);
        }
        public ActionResult Delete(int id)
        {
            TBLDonor t1=con.TBLDonors.Find(id);
            con.TBLDonors.Remove(t1);
            con.SaveChanges();
            return RedirectToAction("GetAll");
        }
        public ActionResult update(int id)
        {
            TBLDonor t1 = con.TBLDonors.Find(id);
            return View(t1);
        }
        public ActionResult updatedata(TBLDonor ndata)
        {
            TBLDonor t1 = con.TBLDonors.Find(ndata.ID_PK);
            t1.Name=ndata.Name;
            t1.Donation_Date=ndata.Donation_Date;
            t1.City=ndata.City;
            t1.Aadhar_Number=ndata.Aadhar_Number;
            t1.Donation_Amount=ndata.Donation_Amount;
            con.SaveChanges();
            return RedirectToAction("GetAll");
        }

    }
}

Views/Donor/GetAll.cshtml
@using Internal_set_a.Models
@model List<TBLDonor>

        <table border="1">
            <tr>
                <td>ID_PK</td>
                <td>Name</td>
                <td>Donation Date</td>
                <td>City</td>
                <td>Aadhar Number</td>
                <td>Donation Amount</td>
                <td></td>
                <td></td>
            </tr>
            @foreach (TBLDonor tr in Model)
            {
                <tr>
                    <td>@tr.ID_PK</td>
                    <td>@tr.Name</td>
                    <td>@tr.Donation_Date</td>
                    <td>@tr.City</td>
                    <td>@tr.Aadhar_Number</td>
                    <td>@tr.Donation_Amount</td>
                    <td>@Html.ActionLink("Update", "update", "Donor", new { id = tr.ID_PK }, null)</td>
                    <td>@Html.ActionLink("Delete", "Delete", "Donor", new { id = tr.ID_PK }, null)</td>

                </tr>
            }
        </table>
   

Views/Donor/Index.cshtml
@using Internal_set_a.Models
@model TBLDonor

        @using (Html.BeginForm("insert", "Donor", FormMethod.Post))
        {
            <label>name</label>
            @Html.TextBoxFor(a => a.Name);
            <label>Donation Date</label>
            @Html.TextBoxFor(a => a.Donation_Date, new { type = "Date" });
            <label>City</label>
            @Html.TextBoxFor(a => a.City);
            <label>Aadhar Number</label>
            @Html.TextBoxFor(a => a.Aadhar_Number);
            <label>Donation Amount</label>
            @Html.TextBoxFor(a => a.Donation_Amount);
            <input type="submit" value="submit" />
        }
    

Views/Donor/Message.cshtml
 
        <h1>
            “Donation amount must be greater than or equal to 10,000”
        </h1>
    

Views/Donor/update.cshtml
@using Internal_set_a.Models
@model TBLDonor
 

        @using (Html.BeginForm("updatedata", "Donor", FormMethod.Post))
        {
            <label>name</label>
            @Html.TextBoxFor(a => a.Name);
            <label>Donation Date</label>
            @Html.TextBoxFor(a => a.Donation_Date, new { type = "Date", id = "bdate" });
            <label>City</label>
            @Html.TextBoxFor(a => a.City);
            <label>Aadhar Number</label>
            @Html.TextBoxFor(a => a.Aadhar_Number);
            <label>Donation Amount</label>
            @Html.TextBoxFor(a => a.Donation_Amount);
            @Html.HiddenFor(a => a.ID_PK);
            <input type="submit" value="submit" />
        }
    
    <script>
        var d=@Model.Donation_Date.ToString("dd");
        var m= @Model.Donation_Date.ToString("MM");
        var y = @Model.Donation_Date.ToString("yyyy");
        var v = y + '-' + (((m.toString().length) == 1) ? ('0'+m) : m) + '-' + (((d.toString().length) == 1) ? ('0'+d) : d);
        var d = document.querySelector("#bdate");
        d.value = v;
    </script>

Views/Shared/Mylayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <div class="myheader">
        <h1>Internal Practical Examination</h1>
        <div class="menulink">
            @Html.ActionLink("go to insert", "Index", "Donor", null, null)
            @Html.ActionLink("list", "GetAll", "Donor", null, null)
        </div>
    </div>
    <div class="maincontainer">
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>